### PR TITLE
Add storybook components/elements

### PR DESCRIPTION
**Pull request by JakeDawkins**
For SYS-2133

### CODE REVIEW

**Comment by johnthepink** [comment]
@JakeDawkins @edolyne Looking good. It looks like some `.jsx` files ended up in the `src` folder. I think we only want `.tsx` files in there. Would you mind taking a look?

Also, as a rule, let's limit builds of the project to their own commit. That way it's easy to distinguish between changes to source, and builds of the site.

**Comment by johnthepink** [comment]
@JakeDawkins awesome thanks. @samclaridge wanna review?

**Comment by samclaridge** [comment]
@JakeDawkins this looks great. One thing I noticed, regarding the Active Progress Bar:
Currently, only the dot is green and the entire bar is grey.
What should happen, is the part of the line preceding the dot should also be green.

@johnthepink I’m not sure if this would be part of Junction, or if this is another example of needing to cross reference Holtzmann?

**Comment by samclaridge** [comment]
@JakeDawkins let’s keep this in Junction.
So, we should add another progress item, so there are 2 dots (as there wouldn’t be a scenario of the progress bar with 1 item).

Then on the Active Bar, the background of the line up to, and including the active dot should be green. The remaining part of the line should stay grey. 

If we can get that added we can merge it through!

**Comment by johnthepink** [comment]
@samclaridge I'm going to merge this for now, and then file an issue to add the progress bar changes later. Just so it's easier to see what has been mapped already.

**Pull request merged**
