### PR TITLE
[WIP] Socials and Icons

### PR DESCRIPTION
**Pull request by johnthepink**
This brings stories for icons, social icons, buttons, and social buttons. The icons story is funny.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
@samclaridge can you review this?

**Comment by samclaridge** [comment]
@johnthepink can you add Instagram to the default social brands and update the color to #8a3ab9?
Thanks!

**Comment by johnthepink** [comment]
@samclaridge added instagram and made it purple

**Comment by jbaxleyiii** [comment]
@samclaridge @johnthepink did we want to go with React markup in the stories or just straight DOM?

**Comment by johnthepink** [comment]
@jbaxleyiii yea that's my bad. i thought it was printing the actual markup in the question mark pop up. i shall fix.

**Comment by johnthepink** [comment]
@jbaxleyiii @samclaridge on another note. Would it be nicer to be able to write React components, but then see the real generated markup?

**Comment by jbaxleyiii** [comment]
@johnthepink I think it would be nice for sure, just not sure if it conflicts with this being just a css doc system

**Comment by johnthepink** [comment]
@jbaxleyiii I think I could go either way on a personal level. As long as the shown markup is not React. 

More broadly, I think most users of Junction won't see the React in the source code of the site, but those that do and want to contribute shouldn't be confused by the React. They should just see some HTML they can add classes to.

With that in mind, I'd vote not abstracting to React components.

I shall fix.

**Comment by jbaxleyiii** [comment]
After a further discussion in slack. We opted to keep this in react. I'll explain more in a guideline for contributing tomorrow 👍

**Pull request merged**
